import { User } from './user';

// export const USERS: User[] = [
//         {
//             "uid": "AABCDE1",
//             "created": 1479201829.0,
//             "email": "admin@gmail.com",
//             "email_verified": 1479203436.576,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE2",
//             "created": 1479088949.0,
//             "email": "afsar8@gmail.com",
//             "email_verified": 1479088978.653,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE3",
//             "created": 1479076092.0,
//             "email": "afsar7@gmail.com",
//             "email_verified": 1479076272.249,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE4",
//             "created": 1479076079.0,
//             "email": "afsar6@gmail.com",
//             "email_verified": 1479076288.366,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE5",
//             "created": 1479076059.0,
//             "email": "afsar5@gmail.com",
//             "email_verified": 1479076263.659,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE71",
//             "created": 1478829620.0,
//             "email": "afsar3@gmail.com",
//             "email_verified": 1478829679.102,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478735019.0,
//             "email": "afsar@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478734763.0,
//             "email": "afsar2@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479201829.0,
//             "email": "admin@gmail.com",
//             "email_verified": 1479203436.576,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479088949.0,
//             "email": "afsar8@gmail.com",
//             "email_verified": 1479088978.653,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076092.0,
//             "email": "afsar7@gmail.com",
//             "email_verified": 1479076272.249,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076079.0,
//             "email": "afsar6@gmail.com",
//             "email_verified": 1479076288.366,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076059.0,
//             "email": "afsar5@gmail.com",
//             "email_verified": 1479076263.659,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478829620.0,
//             "email": "afsar3@gmail.com",
//             "email_verified": 1478829679.102,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478735019.0,
//             "email": "afsar@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478734763.0,
//             "email": "afsar2@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479201829.0,
//             "email": "admin@gmail.com",
//             "email_verified": 1479203436.576,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479088949.0,
//             "email": "afsar8@gmail.com",
//             "email_verified": 1479088978.653,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076092.0,
//             "email": "afsar7@gmail.com",
//             "email_verified": 1479076272.249,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076079.0,
//             "email": "afsar6@gmail.com",
//             "email_verified": 1479076288.366,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076059.0,
//             "email": "afsar5@gmail.com",
//             "email_verified": 1479076263.659,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478829620.0,
//             "email": "afsar3@gmail.com",
//             "email_verified": 1478829679.102,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478735019.0,
//             "email": "afsar@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478734763.0,
//             "email": "afsar2@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479201829.0,
//             "email": "admin@gmail.com",
//             "email_verified": 1479203436.576,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479088949.0,
//             "email": "afsar8@gmail.com",
//             "email_verified": 1479088978.653,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076092.0,
//             "email": "afsar7@gmail.com",
//             "email_verified": 1479076272.249,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076079.0,
//             "email": "afsar6@gmail.com",
//             "email_verified": 1479076288.366,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076059.0,
//             "email": "afsar5@gmail.com",
//             "email_verified": 1479076263.659,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478829620.0,
//             "email": "afsar3@gmail.com",
//             "email_verified": 1478829679.102,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478735019.0,
//             "email": "afsar@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478734763.0,
//             "email": "afsar2@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479201829.0,
//             "email": "admin@gmail.com",
//             "email_verified": 1479203436.576,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479088949.0,
//             "email": "afsar8@gmail.com",
//             "email_verified": 1479088978.653,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076092.0,
//             "email": "afsar7@gmail.com",
//             "email_verified": 1479076272.249,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076079.0,
//             "email": "afsar6@gmail.com",
//             "email_verified": 1479076288.366,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076059.0,
//             "email": "afsar5@gmail.com",
//             "email_verified": 1479076263.659,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478829620.0,
//             "email": "afsar3@gmail.com",
//             "email_verified": 1478829679.102,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478735019.0,
//             "email": "afsar@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478734763.0,
//             "email": "afsar2@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479201829.0,
//             "email": "admin@gmail.com",
//             "email_verified": 1479203436.576,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479088949.0,
//             "email": "afsar8@gmail.com",
//             "email_verified": 1479088978.653,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076092.0,
//             "email": "afsar7@gmail.com",
//             "email_verified": 1479076272.249,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076079.0,
//             "email": "afsar6@gmail.com",
//             "email_verified": 1479076288.366,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076059.0,
//             "email": "afsar5@gmail.com",
//             "email_verified": 1479076263.659,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478829620.0,
//             "email": "afsar3@gmail.com",
//             "email_verified": 1478829679.102,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478735019.0,
//             "email": "afsar@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478734763.0,
//             "email": "afsar2@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479201829.0,
//             "email": "admin@gmail.com",
//             "email_verified": 1479203436.576,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479088949.0,
//             "email": "afsar8@gmail.com",
//             "email_verified": 1479088978.653,
//             "failed_logins": 0,
//             "first_name": "System",
//             "last_name": "Administrator",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076092.0,
//             "email": "afsar7@gmail.com",
//             "email_verified": 1479076272.249,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076079.0,
//             "email": "afsar6@gmail.com",
//             "email_verified": 1479076288.366,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1479076059.0,
//             "email": "afsar5@gmail.com",
//             "email_verified": 1479076263.659,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Jee",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478829620.0,
//             "email": "afsar3@gmail.com",
//             "email_verified": 1478829679.102,
//             "failed_logins": 0,
//             "first_name": "Humpty",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478735019.0,
//             "email": "afsar@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         },
//         {
//             "uid": "AABCDE1",
//             "created": 1478734763.0,
//             "email": "afsar2@gmail.com",
//             "email_verified": 1478736569.207,
//             "failed_logins": 0,
//             "first_name": "Afsar",
//             "last_name": "Imam",
//             "user_banned": false,
//             "user_restricted": false
//         }
//     ]; 
